pipeline {
    agent any

    tools {
        // Specify the Maven version installed in Jenkins
        maven 'Maven local'
        jdk 'jenkins_jdk'
    }

    stages {
        stage('Checkout') {
            steps {
                // Checks out the code from your Git repository
                git 'https://github.com/maukaim/Bulo-Project'
            }
        }

        stage('Build') {
            steps {
                // Builds the project with Maven
                sh 'mvn clean compile'
            }
        }

        stage('Test') {
            steps {
                // Runs unit tests with Maven
                sh 'mvn test'
            }
        }

        stage('Deploy') {
            steps {
                // Deploys the project with Maven
                echo 'Deployed something great'
            }
        }
    }
}