pipeline {
    agent any

    tools {
        // Specify the Maven version installed in Jenkins
        maven 'Maven local'
        jdk 'MyJDK'
    }

    stages {
        stage('Checkout') {
            steps {
                // Checks out the code from your Git repository
                git branch: 'main', url: 'https://github.com/maukaim/Bulo-Project'
            }
        }

        stage('Build') {
            steps {
                dir('back-end') {
                    // Builds the project with Maven
                    sh 'mvn clean compile'
                }
            }
        }

        stage('Test') {
            steps {
                // Runs unit tests with Maven
                dir('back-end'){
                    script {
                        def modules = sh(script: 'mvn --quiet --non-recursive exec:exec -Dexec.executable="pwd"', returnStdout: true).trim().split("\n")
                        def builders = [:]
                        for (module in modules) {
                            builders[module] = {
                                sh "mvn test -pl ${module}"
                            }
                        }
                        parallel builders
                    }
                }
            }
        }

        stage('Deploy') {
            steps {
                // Deploys the project with Maven
                echo 'Deployed something great'
            }
        }
    }
}