pipeline {
    agent any

    tools {
        // It needs to be set in your Jenkins server.
        maven 'Maven local'
        jdk 'MyJDK'
    }

    stages {
        stage('Checkout') {
            steps {
                checkout scm
            }
        }

        stage('Build') {
            steps {
                dir('back-end') {
                    sh 'mvn clean compile'
                }
            }
        }

        stage('Test') {
            steps {
                dir('back-end'){
                    script {
                    sh "mvn test -T 4"
                    }
                }
            }
        }

        stage('Coverage Report'){
            steps{
                jacoco(execPattern: '**/*core*/target/jacoco.exec')
                // Old way to do coverage
//                 recordCoverage(tools: [[parser: 'JACOCO']],
//                         id: 'jacoco', name: 'JaCoCo Coverage',
//                         sourceCodeRetention: 'EVERY_BUILD',
//                         qualityGates: [
//                                 [threshold: 60.0, metric: 'LINE', baseline: 'PROJECT', unstable: true],
//                                 [threshold: 60.0, metric: 'BRANCH', baseline: 'PROJECT', unstable: true]])
            }
        }
    }
}