server:
  port: 10006

maukaim:
  swagger:
    title: Definitions Registry Micro-Service
    description: Service to register and communicate items definitions across the system.
    version: ALPHA
    enabled: true
