/// Flutter icons BuloLogoIcon
/// Copyright (C) 2023 by original authors @ fluttericon.com, fontello.com
/// This font was generated by FlutterIcon.com, which is derived from Fontello.
///
/// To use this font, place it in your fonts/ directory and include the
/// following in your pubspec.yaml
///
/// flutter:
///   fonts:
///    - family:  BuloLogoIcon
///      fonts:
///       - asset: fonts/BuloLogoIcon.ttf
///
/// 
///
import 'package:flutter/widgets.dart';

class BuloLogoIcon {
  BuloLogoIcon._();

  static const _kFontFam = 'BuloLogoIcon';
  static const String? _kFontPkg = null;

  static const IconData bulo_logo_alpha = IconData(0xe800, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData bulo_logo_alpha_full = IconData(0xe801, fontFamily: _kFontFam, fontPackage: _kFontPkg);
}
